### ISSUE TITLE
ee.py在进行CRF运算时报错

### ISSUE THREAD

**Issue by scuyjzh** [bojone/lic2020_baselines#4]
苏神好，在跑ee代码时报如下错误，尝试更换numpy版本后也无果。
Traceback (most recent call last):
  File "ee.py", line 120, in <module>
    output = CRF(output)
  File "/home/xyzhou/anaconda3/envs/xxx/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/xyzhou/anaconda3/envs/xxx/lib/python3.6/site-packages/bert4keras/layers.py", line 29, in new_func
    return func(self, input_shape)
  File "/home/xyzhou/anaconda3/envs/xxx/lib/python3.6/site-packages/bert4keras/layers.py", line 622, in build
    K.set_value(self.trans, K.eval(self.trans) / self.lr_multiplier)
TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

GPU使用的是GeForce RTX 2080 Ti和TITAN Xp
tensorflow 1.13.1
bert4keras 0.7.3
keras 2.31
numpy 1.14.2
PS：相同的代码和环境库在P40上就不报错

**Comment by scuyjzh** [comment]
solved
