### ISSUE TITLE
ee---index out of range

### ISSUE THREAD

**Issue by hurun** [bojone/lic2020_baselines#6]
748/748 [==============================] - 1023s 1s/step - loss: 32.8033 - sparse_accuracy: 0.8512     
 45%|####################2                        | 673/1498 [01:36<01:49,  7.53it/s]Traceback (most recent call last):
  File "Event Extraction_bojone.py", line 243, in <module>
    callbacks=[evaluator]
  File "/usr/local/anaconda3/envs/AI/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/AI/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/anaconda3/envs/AI/lib/python3.6/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/anaconda3/envs/AI/lib/python3.6/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "Event Extraction_bojone.py", line 224, in on_epoch_end
    f1, precision, recall = evaluate(valid_data)
  File "Event Extraction_bojone.py", line 181, in evaluate
    pred_arguments = extract_arguments(text)
  File "Event Extraction_bojone.py", line 171, in extract_arguments
    for w, l in arguments
  File "Event Extraction_bojone.py", line 171, in <dictcomp>
    for w, l in arguments
IndexError: list index out of range

行数可能对不上，但代码没改

**Comment by box0708** [comment]
我也遇到相同问题了 请问解决了吗

**Comment by Kennycao123** [comment]
ie 赛道也遇到同样问题。前后试了两次，分别在训练完第7个epoch和第三个epoch时候遇到index out of range.报的错跟上面也基本相同，请问你们解决了么。
